apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ncugcuccu-tk-tls
spec:
  secretName: ncugcuccu-tk
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: ncugcuccu.tk
  dnsNames:
    - ncugcuccu.tk
    - www.ncugcuccu.tk
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - ncugcuccu.tk
          - www.ncugcuccu.tk